name: Trivy Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-repo-scan:
    runs-on: ubuntu-latest
    name: Repository Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy repository scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-repo-results.sarif'

      - name: Run Trivy repository scan (table format for visibility)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-repo-results.sarif'

  trivy-docker-scan:
    runs-on: ubuntu-latest
    name: Docker Image Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t use-trivy:latest -f docker/Dockerfile docker/

      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'use-trivy:latest'
          format: 'sarif'
          output: 'trivy-docker-results.sarif'

      - name: Run Trivy vulnerability scanner on Docker image (table format for visibility)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'use-trivy:latest'
          format: 'table'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-docker-results.sarif'

  # trivy-terraform-scan:
  #   runs-on: ubuntu-latest
  #   name: Terraform Scan
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Run Trivy scanner on Terraform files
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: 'config'
  #         scan-ref: './terraform'
  #         format: 'sarif'
  #         output: 'trivy-terraform-results.sarif'

  #     - name: Upload Trivy scan results to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v3
  #       if: always()
  #       with:
  #         sarif_file: 'trivy-terraform-results.sarif'

  trivy-combined-report:
    runs-on: ubuntu-latest
    name: Generate Combined Report
    needs: [trivy-repo-scan, trivy-docker-scan]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Build Docker image for combined report
        run: docker build -t use-trivy:latest -f docker/Dockerfile docker/

      - name: Create combined security report
        run: |
          echo "# Trivy Security Scan Report" > security-report.md
          echo "Generated on: $(date)" >> security-report.md
          echo "" >> security-report.md
          
          echo "## Repository Scan Results" >> security-report.md
          echo "Scanning filesystem for vulnerabilities in dependencies and configurations..." >> security-report.md
          echo "" >> security-report.md
          trivy fs . --format table >> security-report.md
          echo "" >> security-report.md
          
          echo "## Docker Image Scan Results" >> security-report.md
          echo "Scanning Docker image 'use-trivy:latest' for vulnerabilities..." >> security-report.md
          echo "" >> security-report.md
          trivy image use-trivy:latest --format table >> security-report.md
          echo "" >> security-report.md
          
          echo "## Summary" >> security-report.md
          echo "This report demonstrates Trivy's capabilities in scanning:" >> security-report.md
          echo "- Filesystem vulnerabilities (dependencies, libraries)" >> security-report.md
          echo "- Docker image vulnerabilities (base image, installed packages)" >> security-report.md
          echo "- Configuration issues and misconfigurations" >> security-report.md

      - name: Upload security report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: security-report.md